[vendor]
name = "The Infinitys"
id = "org.infinite"
url = "https://github.com/The-Infinitys/xross-drums-emulator"
au_manufacturer = "Infi"

[[plugin]]
name = "XrossDrumsEmulator"
bundle_id = "xross-drums-emulator"
crate = "xross-drums-emulator"
category = "instrument"
fourcc = "XDEm"
au_tag = "MIDI"
