use crate::params::saturation::SaturationType;
use crate::presets::KitBlend;

use super::{CompPreset, DrumPreset, EqBandPreset, EqPreset, FxPreset, PartPreset, SaturationPreset, SynthPreset, TransientPreset};

const DEFAULT_COMP: CompPreset = CompPreset {
    threshold: 0.0,
    ratio: 1.0,
    attack: 10.0,
    release: 100.0,
    knee: 0.0,
    makeup: 0.0,
};

const DEFAULT_SAT: SaturationPreset = SaturationPreset {
    drive: 0.0,
    sat_type: SaturationType::Soft,
    hpf: 20.0,
    lpf: 20000.0,
    mix: 100.0,
    out_gain: 0.0,
};

const DEFAULT_FX: FxPreset = FxPreset {
    delay_mix: 0.0,
    delay_time: 300.0,
    delay_fb: 30.0,
    reverb_mix: 0.0,
    reverb_decay: 50.0,
};

pub const PRESET: DrumPreset = DrumPreset {
    name: "FUNK",
    description: "Tight, dry, and super punchy. High-tuned snare and controlled decay for maximum groove.",
    kick: PartPreset {
        pan: 0.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 100.0,
            modern_synth: 20.0,
            synth_808: 0.0,
            synth_909: 0.0,
        },
        synth: SynthPreset {
            freq: 62.0,
            sweep: 0.6,
            decay: 120.0,
            noise: 0.1,
            noise_decay: 10.0,
        },
        eq: EqPreset {
            hp: 40.0,
            low: EqBandPreset {
                freq: 90.0,
                gain: 3.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 500.0,
                gain: -8.0,
                q: 0.5,
            },
            high: EqBandPreset {
                freq: 3500.0,
                gain: 4.0,
                q: 0.7,
            },
            lp: 10000.0,
        },
        comp: CompPreset {
            threshold: -10.0,
            ratio: 4.0,
            attack: 10.0,
            release: 100.0,
            ..DEFAULT_COMP
        },
        transient: TransientPreset {
            attack: 6.0,
            attack_time: 30.0,
            sustain: -6.0,
            sustain_time: 100.0,
            sensitivity: 60.0,
        },
        saturation: SaturationPreset {
            drive: 2.0,
            sat_type: SaturationType::Tape,
            hpf: 50.0,
            lpf: 8000.0,
            mix: 40.0,
            out_gain: 0.0,
        },
        fx: DEFAULT_FX,
    },
    snare: PartPreset {
        pan: 5.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 100.0,
            modern_synth: 30.0,
            synth_808: 0.0,
            synth_909: 20.0,
        },
        synth: SynthPreset {
            freq: 260.0,
            sweep: 0.1,
            decay: 80.0,
            noise: 0.5,
            noise_decay: 100.0,
        },
        eq: EqPreset {
            hp: 200.0,
            low: EqBandPreset {
                freq: 250.0,
                gain: 2.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 900.0,
                gain: 4.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 6000.0,
                gain: 6.0,
                q: 0.7,
            },
            lp: 15000.0,
        },
        comp: CompPreset {
            threshold: -12.0,
            ratio: 3.0,
            attack: 5.0,
            release: 80.0,
            ..DEFAULT_COMP
        },
        transient: TransientPreset {
            attack: 10.0,
            attack_time: 20.0,
            sustain: -2.0,
            sustain_time: 120.0,
            sensitivity: 70.0,
        },
        saturation: SaturationPreset {
            drive: 3.0,
            sat_type: SaturationType::Tube,
            hpf: 150.0,
            lpf: 12000.0,
            mix: 30.0,
            out_gain: 0.0,
        },
        fx: DEFAULT_FX,
    },
    hihat: PartPreset {
        pan: -30.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 100.0,
            modern_synth: 0.0,
            synth_808: 0.0,
            synth_909: 0.0,
        },
        synth: SynthPreset {
            freq: 9500.0,
            sweep: 0.0,
            decay: 50.0,
            noise: 0.6,
            noise_decay: 50.0,
        },
        eq: EqPreset {
            hp: 800.0,
            low: EqBandPreset {
                freq: 800.0,
                gain: -15.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 7000.0,
                gain: 3.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 14000.0,
                gain: 6.0,
                q: 0.7,
            },
            lp: 20000.0,
        },
        comp: DEFAULT_COMP,
        transient: TransientPreset {
            attack: 4.0,
            attack_time: 10.0,
            sustain: -4.0,
            sustain_time: 50.0,
            sensitivity: 80.0,
        },
        saturation: DEFAULT_SAT,
        fx: DEFAULT_FX,
    },
    tom_h: PartPreset {
        pan: -20.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 100.0,
            modern_synth: 0.0,
            synth_808: 0.0,
            synth_909: 0.0,
        },
        synth: SynthPreset {
            freq: 210.0,
            sweep: 0.2,
            decay: 250.0,
            noise: 0.05,
            noise_decay: 10.0,
        },
        eq: EqPreset {
            hp: 120.0,
            low: EqBandPreset {
                freq: 200.0,
                gain: 2.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 800.0,
                gain: -4.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 4000.0,
                gain: 2.0,
                q: 0.7,
            },
            lp: 12000.0,
        },
        comp: DEFAULT_COMP,
        transient: TransientPreset {
            attack: 0.0,
            attack_time: 50.0,
            sustain: 0.0,
            sustain_time: 200.0,
            sensitivity: 50.0,
        },
        saturation: DEFAULT_SAT,
        fx: DEFAULT_FX,
    },
    tom_l: PartPreset {
        pan: 0.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 100.0,
            modern_synth: 0.0,
            synth_808: 0.0,
            synth_909: 0.0,
        },
        synth: SynthPreset {
            freq: 155.0,
            sweep: 0.2,
            decay: 300.0,
            noise: 0.05,
            noise_decay: 10.0,
        },
        eq: EqPreset {
            hp: 100.0,
            low: EqBandPreset {
                freq: 150.0,
                gain: 2.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 700.0,
                gain: -4.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 3500.0,
                gain: 2.0,
                q: 0.7,
            },
            lp: 10000.0,
        },
        comp: DEFAULT_COMP,
        transient: TransientPreset {
            attack: 0.0,
            attack_time: 50.0,
            sustain: 0.0,
            sustain_time: 200.0,
            sensitivity: 50.0,
        },
        saturation: DEFAULT_SAT,
        fx: DEFAULT_FX,
    },
    tom_f: PartPreset {
        pan: 20.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 100.0,
            modern_synth: 0.0,
            synth_808: 0.0,
            synth_909: 0.0,
        },
        synth: SynthPreset {
            freq: 105.0,
            sweep: 0.2,
            decay: 350.0,
            noise: 0.05,
            noise_decay: 10.0,
        },
        eq: EqPreset {
            hp: 80.0,
            low: EqBandPreset {
                freq: 100.0,
                gain: 3.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 500.0,
                gain: -6.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 3000.0,
                gain: 2.0,
                q: 0.7,
            },
            lp: 8000.0,
        },
        comp: DEFAULT_COMP,
        transient: TransientPreset {
            attack: 0.0,
            attack_time: 50.0,
            sustain: 0.0,
            sustain_time: 200.0,
            sensitivity: 50.0,
        },
        saturation: DEFAULT_SAT,
        fx: DEFAULT_FX,
    },
    crash: PartPreset {
        pan: -50.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 100.0,
            modern_synth: 0.0,
            synth_808: 0.0,
            synth_909: 0.0,
        },
        synth: SynthPreset {
            freq: 6000.0,
            sweep: 0.0,
            decay: 1200.0,
            noise: 0.7,
            noise_decay: 1000.0,
        },
        eq: EqPreset {
            hp: 400.0,
            low: EqBandPreset {
                freq: 400.0,
                gain: -15.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 5000.0,
                gain: 1.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 11000.0,
                gain: 4.0,
                q: 0.7,
            },
            lp: 18000.0,
        },
        comp: DEFAULT_COMP,
        transient: TransientPreset {
            attack: 4.0,
            attack_time: 15.0,
            sustain: -10.0,
            sustain_time: 100.0,
            sensitivity: 80.0,
        },
        saturation: DEFAULT_SAT,
        fx: DEFAULT_FX,
    },
    ride: PartPreset {
        pan: 40.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 100.0,
            modern_synth: 0.0,
            synth_808: 0.0,
            synth_909: 0.0,
        },
        synth: SynthPreset {
            freq: 4500.0,
            sweep: 0.0,
            decay: 2000.0,
            noise: 0.5,
            noise_decay: 1500.0,
        },
        eq: EqPreset {
            hp: 600.0,
            low: EqBandPreset {
                freq: 600.0,
                gain: -12.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 4000.0,
                gain: 2.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 12000.0,
                gain: 5.0,
                q: 0.7,
            },
            lp: 18000.0,
        },
        comp: DEFAULT_COMP,
        transient: TransientPreset {
            attack: 5.0,
            attack_time: 15.0,
            sustain: -8.0,
            sustain_time: 200.0,
            sensitivity: 80.0,
        },
        saturation: DEFAULT_SAT,
        fx: DEFAULT_FX,
    },
    master_eq: EqPreset {
        hp: 35.0,
        low: EqBandPreset {
            freq: 80.0,
            gain: 2.0,
            q: 0.7,
        },
        mid: EqBandPreset {
            freq: 1000.0,
            gain: 0.0,
            q: 0.7,
        },
        high: EqBandPreset {
            freq: 8000.0,
            gain: 2.0,
            q: 0.7,
        },
        lp: 18000.0,
    },
    master_comp: CompPreset {
        threshold: -14.0,
        ratio: 3.0,
        attack: 30.0,
        release: 150.0,
        knee: 8.0,
        makeup: 2.0,
    },
    master_clipper_threshold: -0.2,
    master_fx: DEFAULT_FX,
};
