use super::{DrumPreset, EqBandPreset, EqPreset, PartPreset, SynthPreset};

pub const PRESET: DrumPreset = DrumPreset {
    name: "ROCK",
    description: "Punchy and polished. Enhanced dynamics with clear snap and solid weight.",
    kick: PartPreset {
        pan: 0.0,
        heavy: 0.0,
        light: 100.0,
        medium: 0.0,
        electric: 0.0,
        synth: SynthPreset {
            freq: 52.0,
            sweep: 0.7,
            decay: 180.0,
            noise: 0.2,
            noise_decay: 25.0,
        },
        eq: EqPreset {
            low: EqBandPreset {
                freq: 80.0,
                gain: 5.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 400.0,
                gain: -10.0,
                q: 0.5,
            },
            high: EqBandPreset {
                freq: 3000.0,
                gain: 6.0,
                q: 0.7,
            },
        },
        comp_threshold: -14.0,
        trans_attack: 8.0,
        trans_sustain: -4.0,
    },
    snare: PartPreset {
        pan: 5.0,
        heavy: 0.0,
        light: 100.0,
        medium: 0.0,
        electric: 0.0,
        synth: SynthPreset {
            freq: 200.0,
            sweep: 0.2,
            decay: 120.0,
            noise: 0.6,
            noise_decay: 200.0,
        },
        eq: EqPreset {
            low: EqBandPreset {
                freq: 220.0,
                gain: 3.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 800.0,
                gain: -4.0,
                q: 0.5,
            },
            high: EqBandPreset {
                freq: 5000.0,
                gain: 7.0,
                q: 0.7,
            },
        },
        comp_threshold: -16.0,
        trans_attack: 7.0,
        trans_sustain: 3.0,
    },
    hihat: PartPreset {
        pan: -40.0,
        heavy: 0.0,
        light: 100.0,
        medium: 0.0,
        electric: 0.0,
        synth: SynthPreset {
            freq: 500.0,
            sweep: 0.1,
            decay: 50.0,
            noise: 0.7,
            noise_decay: 50.0,
        },
        eq: EqPreset {
            low: EqBandPreset {
                freq: 400.0,
                gain: -18.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 6000.0,
                gain: 2.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 12000.0,
                gain: 5.0,
                q: 0.7,
            },
        },
        comp_threshold: -8.0,
        trans_attack: 3.0,
        trans_sustain: 0.0,
    },
    tom_h: PartPreset {
        pan: -30.0,
        heavy: 0.0,
        light: 100.0,
        medium: 0.0,
        electric: 0.0,
        synth: SynthPreset {
            freq: 170.0,
            sweep: 0.4,
            decay: 300.0,
            noise: 0.1,
            noise_decay: 20.0,
        },
        eq: EqPreset {
            low: EqBandPreset {
                freq: 200.0,
                gain: 4.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 600.0,
                gain: -6.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 4000.0,
                gain: 4.0,
                q: 0.7,
            },
        },
        comp_threshold: -12.0,
        trans_attack: 5.0,
        trans_sustain: 2.0,
    },
    tom_l: PartPreset {
        pan: 0.0,
        heavy: 0.0,
        light: 100.0,
        medium: 0.0,
        electric: 0.0,
        synth: SynthPreset {
            freq: 130.0,
            sweep: 0.4,
            decay: 350.0,
            noise: 0.1,
            noise_decay: 20.0,
        },
        eq: EqPreset {
            low: EqBandPreset {
                freq: 150.0,
                gain: 4.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 500.0,
                gain: -6.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 3500.0,
                gain: 4.0,
                q: 0.7,
            },
        },
        comp_threshold: -12.0,
        trans_attack: 5.0,
        trans_sustain: 2.0,
    },
    tom_f: PartPreset {
        pan: 30.0,
        heavy: 0.0,
        light: 100.0,
        medium: 0.0,
        electric: 0.0,
        synth: SynthPreset {
            freq: 90.0,
            sweep: 0.5,
            decay: 450.0,
            noise: 0.1,
            noise_decay: 20.0,
        },
        eq: EqPreset {
            low: EqBandPreset {
                freq: 100.0,
                gain: 5.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 400.0,
                gain: -8.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 3000.0,
                gain: 4.0,
                q: 0.7,
            },
        },
        comp_threshold: -12.0,
        trans_attack: 5.0,
        trans_sustain: 2.0,
    },
    crash: PartPreset {
        pan: -50.0,
        heavy: 0.0,
        light: 100.0,
        medium: 0.0,
        electric: 0.0,
        synth: SynthPreset {
            freq: 300.0,
            sweep: 0.0,
            decay: 1500.0,
            noise: 0.8,
            noise_decay: 1200.0,
        },
        eq: EqPreset {
            low: EqBandPreset {
                freq: 300.0,
                gain: -20.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 5000.0,
                gain: 2.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 10000.0,
                gain: 4.0,
                q: 0.7,
            },
        },
        comp_threshold: -10.0,
        trans_attack: 4.0,
        trans_sustain: 0.0,
    },
    ride: PartPreset {
        pan: 50.0,
        heavy: 0.0,
        light: 100.0,
        medium: 0.0,
        electric: 0.0,
        synth: SynthPreset {
            freq: 400.0,
            sweep: 0.0,
            decay: 2500.0,
            noise: 0.5,
            noise_decay: 2000.0,
        },
        eq: EqPreset {
            low: EqBandPreset {
                freq: 400.0,
                gain: -15.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 3500.0,
                gain: 1.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 8000.0,
                gain: 5.0,
                q: 0.7,
            },
        },
        comp_threshold: -6.0,
        trans_attack: 3.0,
        trans_sustain: 0.0,
    },
    master_comp_threshold: -18.0,
    master_clipper_threshold: -0.2,
};
