use crate::params::saturation::SaturationType;
use crate::presets::KitBlend;

use super::{
    CompPreset, DrumPreset, EqBandPreset, EqPreset, FxPreset, PartPreset, SaturationPreset,
    SynthPreset, TransientPreset,
};

const DEFAULT_COMP: CompPreset = CompPreset {
    threshold: 0.0,
    ratio: 1.0,
    attack: 10.0,
    release: 100.0,
    knee: 0.0,
    makeup: 0.0,
};

const DEFAULT_SAT: SaturationPreset = SaturationPreset {
    drive: 0.0,
    sat_type: SaturationType::Soft,
    hpf: 20.0,
    lpf: 20000.0,
    mix: 100.0,
    out_gain: 0.0,
};

const DEFAULT_FX: FxPreset = FxPreset {
    delay_mix: 0.0,
    delay_time: 300.0,
    delay_fb: 30.0,
    reverb_mix: 0.0,
    reverb_decay: 50.0,
};

pub const PRESET: DrumPreset = DrumPreset {
    name: "TECHNO",
    description: "Cold and precise electronic groove. Short, punchy hits with clinical processing.",
    kick: PartPreset {
        pan: 0.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 0.0,
            modern_synth: 0.0,
            synth_808: 40.0,
            synth_909: 100.0,
        },
        synth: SynthPreset {
            freq: 50.0,
            sweep: 0.85,
            decay: 200.0,
            noise: 0.3,
            noise_decay: 10.0,
        },
        eq: EqPreset {
            hp: 20.0,
            low: EqBandPreset {
                freq: 60.0,
                gain: 6.0,
                q: 0.8,
            },
            mid: EqBandPreset {
                freq: 300.0,
                gain: -12.0,
                q: 0.4,
            },
            high: EqBandPreset {
                freq: 4000.0,
                gain: 4.0,
                q: 0.7,
            },
            lp: 10000.0,
        },
        comp: CompPreset {
            threshold: -18.0,
            ratio: 6.0,
            attack: 1.0,
            release: 100.0,
            knee: 4.0,
            makeup: 4.0,
        },
        transient: TransientPreset {
            attack: 12.0,
            attack_time: 15.0,
            sustain: -8.0,
            sustain_time: 80.0,
            sensitivity: 70.0,
        },
        saturation: SaturationPreset {
            drive: 6.0,
            sat_type: SaturationType::Hard,
            hpf: 40.0,
            lpf: 6000.0,
            mix: 30.0,
            out_gain: 0.0,
        },
        fx: DEFAULT_FX,
    },
    snare: PartPreset {
        pan: 0.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 0.0,
            modern_synth: 0.0,
            synth_808: 30.0,
            synth_909: 100.0,
        },
        synth: SynthPreset {
            freq: 180.0,
            sweep: 0.1,
            decay: 120.0,
            noise: 0.8,
            noise_decay: 150.0,
        },
        eq: EqPreset {
            hp: 200.0,
            low: EqBandPreset {
                freq: 200.0,
                gain: 2.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 1000.0,
                gain: 3.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 5000.0,
                gain: 6.0,
                q: 0.7,
            },
            lp: 18000.0,
        },
        comp: CompPreset {
            threshold: -12.0,
            ratio: 3.0,
            attack: 10.0,
            release: 100.0,
            knee: 0.0,
            makeup: 0.0,
        },
        transient: TransientPreset {
            attack: 8.0,
            attack_time: 15.0,
            sustain: 0.0,
            sustain_time: 100.0,
            sensitivity: 60.0,
        },
        saturation: SaturationPreset {
            drive: 4.0,
            sat_type: SaturationType::Tape,
            hpf: 200.0,
            lpf: 12000.0,
            mix: 20.0,
            out_gain: 0.0,
        },
        fx: DEFAULT_FX,
    },
    hihat: PartPreset {
        pan: -30.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 0.0,
            modern_synth: 0.0,
            synth_808: 50.0,
            synth_909: 100.0,
        },
        synth: SynthPreset {
            freq: 9000.0,
            sweep: 0.0,
            decay: 30.0,
            noise: 0.9,
            noise_decay: 35.0,
        },
        eq: EqPreset {
            hp: 1500.0,
            low: EqBandPreset {
                freq: 1500.0,
                gain: -15.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 8000.0,
                gain: 4.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 12000.0,
                gain: 8.0,
                q: 0.7,
            },
            lp: 20000.0,
        },
        comp: CompPreset {
            threshold: -8.0,
            ratio: 2.0,
            attack: 0.5,
            release: 30.0,
            knee: 0.0,
            makeup: 0.0,
        },
        transient: TransientPreset {
            attack: 5.0,
            attack_time: 5.0,
            sustain: -6.0,
            sustain_time: 40.0,
            sensitivity: 80.0,
        },
        saturation: DEFAULT_SAT,
        fx: DEFAULT_FX,
    },
    tom_h: PartPreset {
        pan: -20.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 0.0,
            modern_synth: 0.0,
            synth_808: 100.0,
            synth_909: 0.0,
        },
        synth: SynthPreset {
            freq: 180.0,
            sweep: 0.1,
            decay: 100.0,
            noise: 0.0,
            noise_decay: 10.0,
        },
        eq: EqPreset {
            hp: 150.0,
            low: EqBandPreset {
                freq: 250.0,
                gain: 2.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 800.0,
                gain: -6.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 4000.0,
                gain: 2.0,
                q: 0.7,
            },
            lp: 12000.0,
        },
        comp: DEFAULT_COMP,
        transient: TransientPreset {
            attack: 5.0,
            attack_time: 10.0,
            sustain: -4.0,
            sustain_time: 50.0,
            sensitivity: 60.0,
        },
        saturation: DEFAULT_SAT,
        fx: DEFAULT_FX,
    },
    tom_l: PartPreset {
        pan: 0.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 0.0,
            modern_synth: 0.0,
            synth_808: 100.0,
            synth_909: 0.0,
        },
        synth: SynthPreset {
            freq: 140.0,
            sweep: 0.1,
            decay: 120.0,
            noise: 0.0,
            noise_decay: 10.0,
        },
        eq: EqPreset {
            hp: 120.0,
            low: EqBandPreset {
                freq: 180.0,
                gain: 2.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 600.0,
                gain: -6.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 3500.0,
                gain: 2.0,
                q: 0.7,
            },
            lp: 10000.0,
        },
        comp: DEFAULT_COMP,
        transient: TransientPreset {
            attack: 5.0,
            attack_time: 10.0,
            sustain: -4.0,
            sustain_time: 50.0,
            sensitivity: 60.0,
        },
        saturation: DEFAULT_SAT,
        fx: DEFAULT_FX,
    },
    tom_f: PartPreset {
        pan: 20.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 0.0,
            modern_synth: 0.0,
            synth_808: 100.0,
            synth_909: 0.0,
        },
        synth: SynthPreset {
            freq: 90.0,
            sweep: 0.1,
            decay: 150.0,
            noise: 0.0,
            noise_decay: 10.0,
        },
        eq: EqPreset {
            hp: 80.0,
            low: EqBandPreset {
                freq: 130.0,
                gain: 3.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 500.0,
                gain: -8.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 3000.0,
                gain: 2.0,
                q: 0.7,
            },
            lp: 8000.0,
        },
        comp: DEFAULT_COMP,
        transient: TransientPreset {
            attack: 5.0,
            attack_time: 10.0,
            sustain: -4.0,
            sustain_time: 50.0,
            sensitivity: 60.0,
        },
        saturation: DEFAULT_SAT,
        fx: DEFAULT_FX,
    },
    crash: PartPreset {
        pan: -50.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 0.0,
            modern_synth: 0.0,
            synth_808: 0.0,
            synth_909: 100.0,
        },
        synth: SynthPreset {
            freq: 6000.0,
            sweep: 0.0,
            decay: 150.0,
            noise: 0.8,
            noise_decay: 120.0,
        },
        eq: EqPreset {
            hp: 800.0,
            low: EqBandPreset {
                freq: 800.0,
                gain: -18.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 6000.0,
                gain: 2.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 12000.0,
                gain: 4.0,
                q: 0.7,
            },
            lp: 18000.0,
        },
        comp: CompPreset {
            threshold: -10.0,
            ratio: 4.0,
            attack: 0.1,
            release: 30.0,
            knee: 0.0,
            makeup: 0.0,
        },
        transient: TransientPreset {
            attack: 6.0,
            attack_time: 5.0,
            sustain: -15.0,
            sustain_time: 50.0,
            sensitivity: 80.0,
        },
        saturation: DEFAULT_SAT,
        fx: DEFAULT_FX,
    },
    ride: PartPreset {
        pan: 40.0,
        kit_blend: KitBlend {
            heavy: 0.0,
            light: 0.0,
            medium: 0.0,
            modern_synth: 0.0,
            synth_808: 0.0,
            synth_909: 100.0,
        },
        synth: SynthPreset {
            freq: 5500.0,
            sweep: 0.0,
            decay: 250.0,
            noise: 0.6,
            noise_decay: 200.0,
        },
        eq: EqPreset {
            hp: 600.0,
            low: EqBandPreset {
                freq: 600.0,
                gain: -15.0,
                q: 0.7,
            },
            mid: EqBandPreset {
                freq: 4000.0,
                gain: 2.0,
                q: 0.7,
            },
            high: EqBandPreset {
                freq: 10000.0,
                gain: 4.0,
                q: 0.7,
            },
            lp: 18000.0,
        },
        comp: CompPreset {
            threshold: -8.0,
            ratio: 2.0,
            attack: 2.0,
            release: 50.0,
            knee: 0.0,
            makeup: 0.0,
        },
        transient: TransientPreset {
            attack: 3.0,
            attack_time: 10.0,
            sustain: -10.0,
            sustain_time: 80.0,
            sensitivity: 80.0,
        },
        saturation: DEFAULT_SAT,
        fx: DEFAULT_FX,
    },
    master_eq: EqPreset {
        hp: 30.0,
        low: EqBandPreset {
            freq: 55.0,
            gain: 4.0,
            q: 0.8,
        },
        mid: EqBandPreset {
            freq: 350.0,
            gain: -6.0,
            q: 0.5,
        },
        high: EqBandPreset {
            freq: 5000.0,
            gain: 2.0,
            q: 0.7,
        },
        lp: 14000.0,
    },
    master_comp: CompPreset {
        threshold: -20.0,
        ratio: 4.0,
        attack: 5.0,
        release: 100.0,
        knee: 4.0,
        makeup: 5.0,
    },
    master_clipper_threshold: -0.1,
    master_fx: DEFAULT_FX,
};
